### ISSUE TITLE
Ошибка в ожидаемых данных метода resetCode

### ISSUE THREAD

**Issue by mirackle-spb** [rosteleset/ApplicationAPI#2]
Приложение ожидает, что метод resetCode вернет json с единственным полем code, которое будет отображено в приложении как новый код, после сброса.
В документации это отсутствует.
Кроме того, приложение почему-то ожидает, что code будет иметь тип int, тогда как параметр doorCode ответа метода intercom имеет тип string.

**Comment by sbca68** [comment]
исправил описание вызова метода resetCode в apidoc и перегенерировал документацию.
https://rosteleset.github.io/ApplicationAPI/#api-Address-PostAddressResetcode

расхождение типов данных в методах resetCode и intercom действительно имеет место быть.
так сложилось исторически. мы уже сжились с этим.
